### ISSUE TITLE
Role does not work with '--become-method su'

### ISSUE THREAD

**Issue by jaedolph** [linux-system-roles/network#130]
Module throws an exception when run as a non-privileged user who is privilege escalating using '--become-method su'

Example playbook
```
---
- hosts: all
  become: yes
  become_method: su
  become_user: root
  vars:
    network_connections:
    - name: eth0
      state: up
      type: ethernet
      interface_name: eth0
      autoconnect: yes
      ip:
        address: 192.168.1.12/24
        gateway4: 192.168.1.1
        dhcp4: no
        auto6: no
  roles:
  - role: linux-system-roles.network
```
Output
```
[xxx@xxx]$ ansible-playbook playbook.yml -i '192.168.1.12,' -bKk
SSH password: 
BECOME password[defaults to SSH password]: 

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [192.168.1.12]

TASK [linux-system-roles.network : Check which services are running] ***********
ok: [192.168.1.12]

TASK [linux-system-roles.network : Check which packages are installed] *********
ok: [192.168.1.12]

TASK [linux-system-roles.network : Print network provider] *********************
ok: [192.168.1.12] => {
    "msg": "Using network provider: nm"
}

TASK [linux-system-roles.network : Install packages] ***************************
skipping: [192.168.1.12]

TASK [linux-system-roles.network : Enable and start NetworkManager] ************
ok: [192.168.1.12]

TASK [linux-system-roles.network : Enable network service] *********************
skipping: [192.168.1.12]

TASK [linux-system-roles.network : Ensure initscripts network file dependency is present] ***
skipping: [192.168.1.12]

TASK [linux-system-roles.network : Configure networking connection profiles] ***
 [WARNING]: exception: Traceback (most recent call last):   File
"/tmp/ansible_network_connections_payload_j0L_vd/__main__.py", line 2366, in
main     cmd.run()   File
"/tmp/ansible_network_connections_payload_j0L_vd/__main__.py", line 1738, in
run     self.run_prepare()   File
"/tmp/ansible_network_connections_payload_j0L_vd/__main__.py", line 1868, in
run_prepare     Cmd.run_prepare(self)   File
"/tmp/ansible_network_connections_payload_j0L_vd/__main__.py", line 1787, in
run_prepare     ifname=connection["interface_name"]   File
"/tmp/ansible_network_connections_payload_j0L_vd/__main__.py", line 170, in
link_info_find     for li in cls.link_infos(refresh).values():   File
"/tmp/ansible_network_connections_payload_j0L_vd/__main__.py", line 151, in
link_infos     b = SysUtil._link_infos_fetch()   File
"/tmp/ansible_network_connections_payload_j0L_vd/__main__.py", line 130, in
_link_infos_fetch     "perm-address": SysUtil._link_read_permaddress(ifname),
File "/tmp/ansible_network_connections_payload_j0L_vd/__main__.py", line 107,
in _link_read_permaddress     out = Util.check_output(["ethtool", "-P",
ifname])   File "/tmp/ansible_network_connections_payload_j0L_vd/ansible_networ
k_connections_payload.zip/ansible/module_utils/network_lsr/utils.py", line 35,
in check_output     p = subprocess.Popen(argv, stdout=subprocess.PIPE,
stderr=DEVNULL, env=env)   File "/usr/lib64/python2.7/subprocess.py", line 711,
in __init__     errread, errwrite)   File "/usr/lib64/python2.7/subprocess.py",
line 1327, in _execute_child     raise child_exception OSError: [Errno 2] No
such file or directory

fatal: [192.168.1.12]: FAILED! => {"changed": false, "msg": "fatal error: [Errno 2] No such file or directory"}

PLAY RECAP *********************************************************************
192.168.1.12               : ok=5    changed=0    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0  
```

**Comment by pcahyna** [comment]
What distribution and version is the managed host running? What is the full path to `ethtool` on it? And does it work properly when connecting directly as root?

**Comment by jaedolph** [comment]
Distribution is CentOS Linux release 7.6.1810 (Core)
ethtool is at `/usr/sbin/ethtool`
Yes works fine when connecting as root or with --become-method sudo

I have tried with other network configs (teams, bonds) and same exception.

**Comment by tyll** [comment]
I guess the problem is that the way su is configured or Ansible calls su that the PATH variable is not updated to include `/usr/sbin`. Tested here locally:

```shell
ansible -i centos7-demo-cloud, -u centos all -b --become-method su -K  -m shell -a 'id; echo $PATH'
BECOME password: 
centos7-demo-cloud | CHANGED | rc=0 >>
uid=0(root) gid=0(root) Gruppen=0(root) Kontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
/usr/local/bin:/usr/bin
```

**Comment by pcahyna** [comment]
I would consider it a deficiency in the `su` become method, it should behave the same way as the others...

**Comment by pcahyna** [comment]
related: #39
