### ISSUE TITLE
Traceback when running as non-root when ethtool is not in path

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#39]
```
 [WARNING]: exception: Traceback (most recent call last):   File "/tmp/ansible_dkZGH7/ansible_module_network_connections.py", line 2812, in <module>     cmd.run()   File
"/tmp/ansible_dkZGH7/ansible_module_network_connections.py", line 2398, in run     self.run_prepare()   File "/tmp/ansible_dkZGH7/ansible_module_network_connections.py", line 2473, in run_prepare
Cmd.run_prepare(self)   File "/tmp/ansible_dkZGH7/ansible_module_network_connections.py", line 2443, in run_prepare     li_ifname = SysUtil.link_info_find(ifname = connection['interface_name'])   File
"/tmp/ansible_dkZGH7/ansible_module_network_connections.py", line 404, in link_info_find     for li in cls.link_infos(refresh).values():   File "/tmp/ansible_dkZGH7/ansible_module_network_connections.py", line
387, in link_infos     b = SysUtil._link_infos_fetch()   File "/tmp/ansible_dkZGH7/ansible_module_network_connections.py", line 368, in _link_infos_fetch     'perm-address':
SysUtil._link_read_permaddress(ifname),   File "/tmp/ansible_dkZGH7/ansible_module_network_connections.py", line 346, in _link_read_permaddress     out = Util.check_output(['ethtool', '-P', ifname])   File
"/tmp/ansible_dkZGH7/ansible_module_network_connections.py", line 76, in check_output     p = subprocess.Popen(argv, stdout=subprocess.PIPE, stderr=DEVNULL, env=ev)   File "/usr/lib64/python2.7/subprocess.py",
line 711, in __init__     errread, errwrite)   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child     raise child_exception OSError: [Errno 2] No such file or directory

fatal: [ansibletest]: FAILED! => {"changed": false, "msg": "fatal error: [Errno 2] No such file or directory"}
```

Happened on CentOS 7.

**Comment by pcahyna** [comment]
Is it related to e0c492eeb5a6511687753a58012efd7069ed5066? Is it a version before or after that change?
Is the role supposed to do anything useful if run as non-root?

**Comment by tyll** [comment]
The offending line was last changed in  2cd6d3dbdf564d44b45e8f30b2ac90fa50acedc2 on 17 Jul 2017:   https://github.com/linux-system-roles/network/blob/b5143f8b44d6bae6a8ed922d500678961247b48d/library/network_connections.py#L346

The problem is that it just says ethtool instead of /usr/sbin/ethtool. My assumpition is that it is currently just bad error reporting and not a functional problem. Usually root access is required but this command could also be run as non-root, e.g. ```ethtool -P lo```. Other parts of the role already complain when they need more privileges.

**Comment by tyll** [comment]
And it is not related to  e0c492e other than that commit probably fixed a similar issue (ethtools not being available).

**Comment by pcahyna** [comment]
Actually, could this be circumvented completely by using the proper ioctl for querying the permanent MAC address, instead of screen scraping?
