### ISSUE TITLE
pkey interfaces cannot be deleted reliably

### ISSUE THREAD

**Issue by codeRhein** [linux-system-roles/network#524]
Hello, so we found an issue that it seems infiniband pkey interface cannot be deleted, for example running script:
```
  - name: 'ib0.8008'
    persistent_state: absent
```
and interface is still there without reporting error, while increase verbosity you can see: 
```
'Traceback (most recent call last):  
File "/tmp/ansible_network_connections_payload_jvvf4xj9/ansible_network_connections_payload.zip/ansible/module_utils/network_lsr/nm/connection.py", line 116, in _nm_profile_volatile_update2_call_back
 
File "/tmp/ansible_network_connections_payload_jvvf4xj9/ansible_network_connections_payload.zip/ansible/module_utils/network_lsr/nm/client.py", line 96, in fail\nansible.module_utils.network_lsr.nm.error.LsrNetworkNmError: Connection volatilize aborted on ib0.8008/5ece4f41-3fe7-4a8d-ba10-3dd3549c6bcd: error=unknown'
```

**Comment by codeRhein** [comment]
The interface can be deleted manually.

**Comment by liangwen12year** [comment]
Hi, how did you increase the verbosity ? `ansible-playbook -vvv` ?

**Comment by liangwen12year** [comment]
And what version of the role that you are using ?

**Comment by codeRhein** [comment]
> 

Sorry for the late reply, yes it is!

> Hi, how did you increase the verbosity ? `ansible-playbook -vvv` ?

**Comment by codeRhein** [comment]
> And what version of the role that you are using ?

ansible [core 2.13.2]
python version = 3.10.6 (main, Aug  8 2022, 04:20:17) [Clang 13.1.6 (clang-1316.0.21.2.5)]
jinja version = 3.1.2

**Comment by liangwen12year** [comment]
I investigated the issue a bit,  it is a bug in the NM, `<warn>  [1661784263.9220] ifcfg-rh:     InfiniBand connection specified PKEY but not DEVICE`, so I will create a pr in the NM and attach the link shortly.

**Comment by codeRhein** [comment]
> I investigated the issue a bit, it is a bug in the NM, `<warn> [1661784263.9220] ifcfg-rh: InfiniBand connection specified PKEY but not DEVICE`, so I will create a pr in the NM and attach the link shortly.

OK, thanks so much !

**Comment by liangwen12year** [comment]
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/1357

**Comment by liangwen12year** [comment]
The NM upstream PR was merged.

**Comment by codeRhein** [comment]
> The NM upstream PR was merged.
Thanks so much ! So this network role will catch up new NM package including the fix in the next release, right ?

**Comment by liangwen12year** [comment]
I think that it depends on the NetworkManager version the managed host is installed, the bug was fixed since NM-1.41.2. 

There was not any change related to the network role.

**Comment by codeRhein** [comment]
> I think that it depends on the NetworkManager version the managed host is installed, the bug was fixed since NM-1.41.2.

OK then we can close this ticket, thanks so much!
